"""Initial migration

Revision ID: d6794f51f209
Revises: 
Create Date: 2026-07-15 14:20:40.847872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6794f51f209'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_issues_proyecto_status'), table_name='issues')
    op.drop_index(op.f('idx_issues_sprint'), table_name='issues')
    op.drop_index(op.f('idx_kpis_proyecto_fecha'), table_name='kpis_historicos')
    op.drop_index(op.f('idx_logs_fecha'), table_name='logs_sincronizacion')
    op.drop_index(op.f('idx_transiciones_issue_fecha'), table_name='transiciones_estado_issue')
    op.drop_constraint(op.f('usuarios_jira_account_id_key'), 'usuarios', type_='unique')
    op.create_index(op.f('ix_usuarios_id_usuario'), 'usuarios', ['id_usuario'], unique=False)
    op.create_index(op.f('ix_usuarios_jira_account_id'), 'usuarios', ['jira_account_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_jira_account_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id_usuario'), table_name='usuarios')
    op.create_unique_constraint(op.f('usuarios_jira_account_id_key'), 'usuarios', ['jira_account_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_transiciones_issue_fecha'), 'transiciones_estado_issue', ['id_jira', 'fecha_cambio'], unique=False)
    op.create_index(op.f('idx_logs_fecha'), 'logs_sincronizacion', [sa.literal_column('fecha_ejecucion DESC')], unique=False)
    op.create_index(op.f('idx_kpis_proyecto_fecha'), 'kpis_historicos', ['id_proyecto', 'fecha_calculo'], unique=False)
    op.create_index(op.f('idx_issues_sprint'), 'issues', ['id_sprint'], unique=False)
    op.create_index(op.f('idx_issues_proyecto_status'), 'issues', ['id_proyecto', 'status_actual'], unique=False)
    # ### end Alembic commands ###
